runtime: python311
entrypoint: gunicorn app:app
handlers:
- url: /.*
  script: auto
env_variables:
  AI_KEY: 'AIzaSyCdpyBPmDko91aN1yIRWuRf6UpK7cXByVg'
  SUPA_URL: 'https://ausntzmvrqbrafcxcflu.supabase.co'
  SUPA_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1c250em12cnFicmFmY3hjZmx1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcyNTc1NjY5MiwiZXhwIjoyMDQxMzMyNjkyfQ.fbx9b-vDD9dRnl2b3mjsrtC9mreXGUOzaQ24m5zysOk'
  PORT: 10000